### ISSUE TITLE
Generate Client Key with KEYGEN Request

### ISSUE THREAD

**Issue by xzinkus** [WhiteHatCP/seclab-listener#2]
Let's make a "client-init" request that connects via SSL and receives a new PSK.

Format:

```
1 byte 0xAA
8 bytes timestamp
HMAC keyed with old PSK
```

Response:

```
1 byte 0x55
8 bytes timestamp
32 bytes new key
```

Thoughts?

**Comment by xzinkus** [comment]
1. Should we HMAC the response
2. Any issues with this design?

**Comment by slashnick** [comment]
Similar to #1, the response is already encrypted, HMAC'd, and authenticated by TLS, since we trust the server with the pinned public key, so I don't think we need to HMAC the response.

The rest looks good to me.  This would be a problem if there were multiple clients using the service as they would have to sync keys, but since it's just one Pi I think we should be fine.

**Comment by xzinkus** [comment]
Cool :+1: I'll edit the spec
